import fs from "fs";
import path from "path";
import { createCanvas } from '@napi-rs/canvas';

export async function generateSummaryImage(total, top5, timestamp) {
  const width = 1200, height = 630;
  const canvas = createCanvas(width, height);
  const ctx = canvas.getContext("2d");

  ctx.fillStyle = "#fff";
  ctx.fillRect(0, 0, width, height);
  ctx.fillStyle = "#111";
  ctx.font = "bold 36px Sans";
  ctx.fillText("Countries Summary", 40, 70);

  ctx.font = "24px Sans";
  ctx.fillText(`Total countries: ${total}`, 40, 120);
  ctx.fillText(`Refreshed at: ${new Date(timestamp).toISOString()}`, 40, 160);
  ctx.font = "22px Sans";
  ctx.fillText("Top 5 by estimated GDP:", 40, 220);
  ctx.font = "20px Sans";

  top5.forEach((c, i) => {
    const line = `${i + 1}. ${c.name} — ${Number(c.estimated_gdp).toLocaleString(undefined, { maximumFractionDigits: 2 })}`;
    ctx.fillText(line, 60, 260 + i * 36);
  });

  ctx.font = "16px Sans";
  ctx.fillStyle = "#444";
  ctx.fillText("Generated by country-exchange-api", 40, height - 40);

  const outPath = path.resolve("cache");
  if (!fs.existsSync(outPath)) fs.mkdirSync(outPath, { recursive: true });
  fs.writeFileSync(path.join(outPath, "summary.png"), canvas.toBuffer("image/png"));
}
